import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class ParisTask2 {
    public static void main(String[] args) throws InterruptedException {
        System.setProperty("webdriver.chrome.driver", "D:/Java_automation/chromedriver_win32/chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.get("https://www.booking.com/");
        driver.manage().window().maximize();
        WebElement searchCity = driver.findElement(By.xpath("//input[@name='ss']"));
        searchCity.sendKeys("Paris");
        Thread.sleep(2000);
        WebElement firstOption = driver.findElement(By.xpath("(.//li[@role='option'])[1]"));
        firstOption.click();
        Thread.sleep(2000);

        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime nowDate = LocalDateTime.now();
        LocalDateTime plusTreeDays = nowDate.plusDays(3);
        String newDate = plusTreeDays.format(dateTimeFormatter);
        System.out.println(newDate);
        String[] dateArray = newDate.split(" ");
        WebElement checkIn = driver.findElement(By.xpath(".//td[@data-date='" + dateArray[0] + "']"));
        checkIn.click();
        DateTimeFormatter dateTimeFormatter10 = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime nowDate10 = LocalDateTime.now();
        LocalDateTime plusTenDays = nowDate10.plusDays(10);
        String newDate10 = plusTenDays.format(dateTimeFormatter10);
        String[] dateArray10 = newDate10.split(" ");
        WebElement checkOut = driver.findElement(By.xpath(".//td[@data-date='" + dateArray10[0] + "']"));
        checkOut.click();
        WebElement guests = driver.findElement(By.id("xp__guests__toggle"));
        guests.click();
        WebElement plusGuestButton = driver.findElement(By.xpath("(.//button[@class='bui-button bui-button--secondary bui-stepper__add-button '])[1]"));
        plusGuestButton.click();
        plusGuestButton.click();
        WebElement plusRoomButton = driver.findElement(By.xpath("(.//button[@class='bui-button bui-button--secondary bui-stepper__add-button '])[3]"));
        plusRoomButton.click();
        WebElement submitButton = driver.findElement(By.xpath(".//button[@data-sb-id='main']"));
        submitButton.click();
        WebElement budget = driver.findElement(By.xpath("(.//div[@class='bui-checkbox__label filter_item css-checkbox'])[5]"));
        budget.click();
        Thread.sleep(2000);
        WebElement lowPriceFirst = driver.findElement(By.xpath(".//a[@data-category='price']"));
        lowPriceFirst.click();
        Thread.sleep(2000);
        WebElement lessExpensive = driver.findElement(By.xpath("(.//div[@class='bui-price-display__value prco-inline-block-maker-helper'])[1]"));
        int budgetPrisePerNight = 952;
        int nights = 7;
        Matcher matcher = Pattern.compile("[-]?[0-9]+(.[0-9]+)?").matcher(lessExpensive.getText());
        matcher.find();
        String priceOnlyNumbers = matcher.group();
        System.out.println("Price per night is: " + priceOnlyNumbers);
        String value = priceOnlyNumbers.replaceAll(",", "");
        int priceBookingHas = (Integer.parseInt(value)) / nights;
        System.out.println((priceBookingHas >= budgetPrisePerNight) ? "Price NOT lower than the specified range" : "Price is lower");
        WebElement hotelLink = driver.findElement(By.xpath("(.//a[@class='hotel_name_link url'])[1]"));
        hotelLink.click();
        Thread.sleep(4000);
        Set<String> windowHandles = driver.getWindowHandles();
        for (String window : windowHandles) {
            driver.switchTo().window(window);
        }
        Thread.sleep(3000);
        WebElement selectRooms = driver.findElement(By.xpath("(.//select[@class='hprt-nos-select'])[1]"));
        selectRooms.click();
        Thread.sleep(1000);
        Select select = new Select(selectRooms);
        select.selectByValue("1");
        WebElement reserveButton = driver.findElement(By.xpath(".//div[@class='hprt-reservation-cta']"));
        reserveButton.click();
        Thread.sleep(3000);
        WebElement radioButtonNo = driver.findElement(By.xpath(".//input[@id='bp_travel_purpose_leasure']"));
        radioButtonNo.click();
        WebElement firstName = driver.findElement(By.id("firstname"));
        firstName.sendKeys("Margarita");
        WebElement lastName = driver.findElement(By.id("lastname"));
        lastName.sendKeys("Fedorova");
        WebElement email = driver.findElement(By.id("email"));
        email.sendKeys("margaritapoteychuk@gmail.com");
        WebElement emailAgain = driver.findElement(By.id("email_confirm"));
        emailAgain.sendKeys("margaritapoteychuk@gmail.com");
        WebElement bookForMe = driver.findElement(By.id("notstayer_false"));
        bookForMe.click();
        Thread.sleep(3000);
        WebElement finalDetailsButton = driver.findElement(By.xpath("/html/body/div[2]/div/div[3]/div/div[3]/div[3]/div/div/form/div[3]/div[1]/div[2]"));
        finalDetailsButton.click();
        Thread.sleep(3000);
        WebElement phone = driver.findElement(By.id("phone"));
        phone.sendKeys("295965752");
        //WebElement payNow = driver.findElement(By.xpath(".//label[@for='pay-now']"));
        //payNow.click();
        WebElement cardType = driver.findElement(By.id("cc_type"));
        Select select2 = new Select(cardType);
        select2.selectByValue("Visa");
        WebElement cardNumber = driver.findElement(By.id("cc_number"));
        cardNumber.sendKeys("4242 4242 4242 4242");
        WebElement yearCard = driver.findElement(By.id("ccYear"));
        Select select3 = new Select(yearCard);
        select3.selectByValue("2022");
        //WebElement cvcCode = driver.findElement(By.id("cc_cvc"));
        //cvcCode.sendKeys("222");
        WebElement completeBooking = driver.findElement(By.xpath("/html/body/div[2]/div/div[3]/div[1]/form/div[2]/div[3]/div/div[4]/div[1]/button[2]"));
        completeBooking.click();
        Thread.sleep(10000);
        WebElement alertMessage = driver.findElement(By.xpath(".//h1[@class='reassurance__title']"));
        System.out.println(alertMessage.getText());
        driver.quit();
    }
}
